version: "3.1"

language: "es"

# Pipeline de procesamiento
pipeline:
- name: WhitespaceTokenizer
- name: RegexEntityExtractor
- name: CountVectorsFeaturizer
- name: DIETClassifier
  epochs: 100        # Puedes ajustar el número de épocas según tu necesidad.
- name: EntitySynonymMapper
- name: ResponseSelector
  epochs: 100
- name: FallbackClassifier
  threshold: 0.3        # Si la confianza es menor a 0.3, el clasificador activa el fallback.

# Políticas
policies:
  # Política de predicción de las intenciones y entidades con el clasificador DIET
- name: MemoizationPolicy
  max_history: 5        # Ajusta el historial de las predicciones previas.

  # Política de respuesta predicha basada en el estado del diálogo (Rasa 3.1)
- name: RulePolicy

  # Política de seguimiento de conversación: Establece cómo manejar el diálogo entre los pasos
- name: TEDPolicy
  max_history: 5
  epochs: 100        # Se ajusta el número de épocas para mejorar la capacidad de predicción.

  # Si la predicción de la intención o la clasificación es de baja confianza, activa el fallback.
- name: RulePolicy    # Usamos esta política para manejar las reglas y fallback.
assistant_id: 20250501-225225-white-mill
